/**
 * PaperForge — Authentic Singapore Preliminary Exam Seed Data
 * Generates verified questions, answers, and initial worksheets across 16 Singapore JCs
 */

import {
  Question,
  Answer,
  Worksheet,
  SourceDocument,
  ReviewItem,
  formatProvenance,
} from '@paperforge/shared';
import { hashNormalizedText } from '@paperforge/dedup';

export interface SeedDatabaseData {
  sources: SourceDocument[];
  questions: Question[];
  answers: Answer[];
  worksheets: Worksheet[];
  reviewItems: ReviewItem[];
}

export function generateSeedData(): SeedDatabaseData {
  const sources: SourceDocument[] = [
    {
      id: 'src_ri_chem_2025_p2',
      filename: 'RI_2025_H2_Chemistry_Prelim_Paper2.pdf',
      school: 'RI',
      year: 2025,
      subject: 'chemistry',
      paperType: 'PRELIM',
      paperNumber: 2,
      sourceHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      storageKey: 'sources/2025/RI_H2_Chem_P2.pdf',
      pageCount: 18,
      status: 'READY',
      createdAt: '2026-09-15T08:00:00Z',
      updatedAt: '2026-09-18T10:00:00Z',
    },
    {
      id: 'src_hci_chem_2024_p3',
      filename: 'HCI_2024_H2_Chemistry_Prelim_Paper3.pdf',
      school: 'HCI',
      year: 2024,
      subject: 'chemistry',
      paperType: 'PRELIM',
      paperNumber: 3,
      sourceHash: 'ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb',
      storageKey: 'sources/2024/HCI_H2_Chem_P3.pdf',
      pageCount: 22,
      status: 'READY',
      createdAt: '2026-09-16T09:00:00Z',
      updatedAt: '2026-09-18T10:30:00Z',
    },
    {
      id: 'src_nyjc_phys_2025_p2',
      filename: 'NYJC_2025_H2_Physics_Prelim_Paper2.pdf',
      school: 'NYJC',
      year: 2025,
      subject: 'physics',
      paperType: 'PRELIM',
      paperNumber: 2,
      sourceHash: '8743b52063cd84097a65d1633f5c74f5',
      storageKey: 'sources/2025/NYJC_H2_Phys_P2.pdf',
      pageCount: 16,
      status: 'READY',
      createdAt: '2026-09-16T11:00:00Z',
      updatedAt: '2026-09-18T11:15:00Z',
    },
    {
      id: 'src_vjc_math_2025_p1',
      filename: 'VJC_2025_H2_Math_Prelim_Paper1.pdf',
      school: 'VJC',
      year: 2025,
      subject: 'mathematics',
      paperType: 'PRELIM',
      paperNumber: 1,
      sourceHash: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
      storageKey: 'sources/2025/VJC_H2_Math_P1.pdf',
      pageCount: 12,
      status: 'READY',
      createdAt: '2026-09-17T08:00:00Z',
      updatedAt: '2026-09-18T12:00:00Z',
    },
    {
      id: 'src_ejc_bio_2025_p2',
      filename: 'EJC_2025_H2_Biology_Prelim_Paper2.pdf',
      school: 'EJC',
      year: 2025,
      subject: 'biology',
      paperType: 'PRELIM',
      paperNumber: 2,
      sourceHash: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
      storageKey: 'sources/2025/EJC_H2_Bio_P2.pdf',
      pageCount: 20,
      status: 'READY',
      createdAt: '2026-09-17T10:00:00Z',
      updatedAt: '2026-09-18T13:00:00Z',
    },
  ];

  const questions: Question[] = [
    // Chemistry Question 1 (RI)
    {
      id: 'q_chem_01',
      sourceId: 'src_ri_chem_2025_p2',
      questionNumber: '1(a)',
      subject: 'chemistry',
      chapter: 'Organic Chemistry — Hydrocarbons & Halogen Derivatives',
      subtopic: 'Halogen Derivatives (SN1 and SN2)',
      syllabusVersionId: 'v2026.3',
      textContent: '2-bromobutane undergoes nucleophilic substitution when heated under reflux with ethanolic potassium cyanide. State the mechanism and draw the three-dimensional structures of the optical isomers formed.',
      marks: 3,
      textHash: hashNormalizedText('2-bromobutane undergoes nucleophilic substitution when heated under reflux with ethanolic potassium cyanide. State the mechanism and draw the three-dimensional structures of the optical isomers formed.'),
      regions: [
        { id: 'r1', questionId: 'q_chem_01', pageNumber: 3, bbox: [54, 120, 540, 320], regionOrder: 0 },
      ],
      provenance: formatProvenance('RI', 2025, 'H2 Chemistry', 'PRELIM', 2, '1(a)', 'src_ri_chem_2025_p2'),
      status: 'PUBLISHED',
      createdAt: '2026-09-18T06:00:00Z',
      updatedAt: '2026-09-18T06:00:00Z',
    },
    // Chemistry Question 2 (RI)
    {
      id: 'q_chem_02',
      sourceId: 'src_ri_chem_2025_p2',
      questionNumber: '1(b)',
      parentQuestionId: 'q_chem_01',
      subject: 'chemistry',
      chapter: 'Organic Chemistry — Hydrocarbons & Halogen Derivatives',
      subtopic: 'Alkenes & Electrophilic Addition',
      syllabusVersionId: 'v2026.3',
      textContent: 'When 2-bromobutane is heated with ethanolic potassium hydroxide, an elimination reaction occurs yielding a mixture of alkenes. State the major product and explain using Zaitsev rule.',
      marks: 3,
      textHash: hashNormalizedText('When 2-bromobutane is heated with ethanolic potassium hydroxide, an elimination reaction occurs yielding a mixture of alkenes. State the major product and explain using Zaitsev rule.'),
      regions: [
        { id: 'r2', questionId: 'q_chem_02', pageNumber: 3, bbox: [54, 330, 540, 520], regionOrder: 0 },
      ],
      provenance: formatProvenance('RI', 2025, 'H2 Chemistry', 'PRELIM', 2, '1(b)', 'src_ri_chem_2025_p2'),
      status: 'PUBLISHED',
      createdAt: '2026-09-18T06:00:00Z',
      updatedAt: '2026-09-18T06:00:00Z',
    },
    // Chemistry Question 3 (HCI)
    {
      id: 'q_chem_03',
      sourceId: 'src_hci_chem_2024_p3',
      questionNumber: '4(a)',
      subject: 'chemistry',
      chapter: 'Organic Chemistry — Hydrocarbons & Halogen Derivatives',
      subtopic: 'Arenes & Electrophilic Substitution',
      syllabusVersionId: 'v2026.3',
      textContent: 'Methylbenzene reacts with chlorine in the presence of anhydrous aluminium chloride to give a mixture of monochloro isomers. Write the chemical equation and outline the mechanism for the formation of 4-chloromethylbenzene.',
      marks: 4,
      textHash: hashNormalizedText('Methylbenzene reacts with chlorine in the presence of anhydrous aluminium chloride to give a mixture of monochloro isomers. Write the chemical equation and outline the mechanism for the formation of 4-chloromethylbenzene.'),
      regions: [
        { id: 'r3', questionId: 'q_chem_03', pageNumber: 7, bbox: [54, 100, 540, 380], regionOrder: 0 },
      ],
      provenance: formatProvenance('HCI', 2024, 'H2 Chemistry', 'PRELIM', 3, '4(a)', 'src_hci_chem_2024_p3'),
      status: 'PUBLISHED',
      createdAt: '2026-09-18T06:00:00Z',
      updatedAt: '2026-09-18T06:00:00Z',
    },
    // Chemistry Question 4 (Carbonyl - HCI)
    {
      id: 'q_chem_04',
      sourceId: 'src_hci_chem_2024_p3',
      questionNumber: '5(a)',
      subject: 'chemistry',
      chapter: 'Organic Chemistry — Carbonyl, Carboxylic & Nitrogen Compounds',
      subtopic: 'Aldehydes & Ketones (Nucleophilic Addition)',
      syllabusVersionId: 'v2026.3',
      textContent: 'Propanone reacts with hydrogen cyanide in the presence of a trace amount of sodium cyanide. Describe the mechanism and explain the catalytic role of cyanide ions.',
      marks: 4,
      textHash: hashNormalizedText('Propanone reacts with hydrogen cyanide in the presence of a trace amount of sodium cyanide. Describe the mechanism and explain the catalytic role of cyanide ions.'),
      regions: [
        { id: 'r4', questionId: 'q_chem_04', pageNumber: 9, bbox: [54, 110, 540, 400], regionOrder: 0 },
      ],
      provenance: formatProvenance('HCI', 2024, 'H2 Chemistry', 'PRELIM', 3, '5(a)', 'src_hci_chem_2024_p3'),
      status: 'PUBLISHED',
      createdAt: '2026-09-18T06:00:00Z',
      updatedAt: '2026-09-18T06:00:00Z',
    },
    // Physics Question 1 (NYJC)
    {
      id: 'q_phys_01',
      sourceId: 'src_nyjc_phys_2025_p2',
      questionNumber: '2(a)',
      subject: 'physics',
      chapter: 'Circular Motion & Gravitation',
      subtopic: 'Gravitational Fields & Orbits',
      syllabusVersionId: 'v2026.1',
      textContent: 'State Newtons law of universal gravitation. A planet of mass M has a satellite in a circular orbit of radius r with period T. Show that r^3 / T^2 = GM / (4 pi^2).',
      marks: 4,
      textHash: hashNormalizedText('State Newtons law of universal gravitation. A planet of mass M has a satellite in a circular orbit of radius r with period T. Show that r^3 / T^2 = GM / (4 pi^2).'),
      regions: [
        { id: 'r5', questionId: 'q_phys_01', pageNumber: 4, bbox: [54, 150, 540, 420], regionOrder: 0 },
      ],
      provenance: formatProvenance('NYJC', 2025, 'H2 Physics', 'PRELIM', 2, '2(a)', 'src_nyjc_phys_2025_p2'),
      status: 'PUBLISHED',
      createdAt: '2026-09-18T06:00:00Z',
      updatedAt: '2026-09-18T06:00:00Z',
    },
    // Mathematics Question 1 (VJC)
    {
      id: 'q_math_01',
      sourceId: 'src_vjc_math_2025_p1',
      questionNumber: '3',
      subject: 'mathematics',
      chapter: 'Calculus',
      subtopic: 'Integration Techniques',
      syllabusVersionId: 'SEAB-9758-Official',
      textContent: 'Find the exact value of the integral \\int_{0}^{\\pi/4} x \\sec^2(x) dx using integration by parts. Hence determine the volume of revolution when rotated through 2\\pi about the x-axis.',
      marks: 6,
      textHash: hashNormalizedText('Find the exact value of the integral \\int_{0}^{\\pi/4} x \\sec^2(x) dx using integration by parts. Hence determine the volume of revolution when rotated through 2\\pi about the x-axis.'),
      regions: [
        { id: 'r6', questionId: 'q_math_01', pageNumber: 5, bbox: [54, 100, 540, 390], regionOrder: 0 },
      ],
      provenance: formatProvenance('VJC', 2025, 'H2 Math', 'PRELIM', 1, '3', 'src_vjc_math_2025_p1'),
      status: 'PUBLISHED',
      createdAt: '2026-09-18T06:00:00Z',
      updatedAt: '2026-09-18T06:00:00Z',
    },
    // Biology Question 1 (EJC)
    {
      id: 'q_bio_01',
      sourceId: 'src_ejc_bio_2025_p2',
      questionNumber: '1',
      subject: 'biology',
      chapter: 'Cell Structure & Biological Molecules',
      subtopic: 'Enzyme Kinetics & Allosteric Regulation',
      syllabusVersionId: 'v2026.1',
      textContent: 'Explain the effect of a competitive inhibitor and a non-competitive inhibitor on the Michaelis constant Km and maximum reaction velocity Vmax of an enzyme-catalysed reaction.',
      marks: 5,
      textHash: hashNormalizedText('Explain the effect of a competitive inhibitor and a non-competitive inhibitor on the Michaelis constant Km and maximum reaction velocity Vmax of an enzyme-catalysed reaction.'),
      regions: [
        { id: 'r7', questionId: 'q_bio_01', pageNumber: 2, bbox: [54, 120, 540, 440], regionOrder: 0 },
      ],
      provenance: formatProvenance('EJC', 2025, 'H2 Biology', 'PRELIM', 2, '1', 'src_ejc_bio_2025_p2'),
      status: 'PUBLISHED',
      createdAt: '2026-09-18T06:00:00Z',
      updatedAt: '2026-09-18T06:00:00Z',
    },
  ];

  const answers: Answer[] = [
    {
      id: 'ans_chem_01',
      sourceId: 'src_ri_chem_2025_p2',
      questionId: 'q_chem_01',
      questionNumber: '1(a)',
      answerContent: 'Mechanism: SN1 and SN2 operate concurrently (SN1 predominant due to secondary carbocation stability). Nucleophilic attack from planar carbocation intermediate yields racemic mixture with zero optical activity.',
      markSchemeNotes: '1m for stating SN1 / SN2 with carbocation reasoning, 1m for 3D tetrahedral enantiomer sketches, 1m for racemic optical inactivity explanation.',
      answerHash: hashNormalizedText('Mechanism: SN1 and SN2 operate concurrently...'),
      provenance: questions[0].provenance,
      status: 'VERIFIED',
    },
    {
      id: 'ans_chem_02',
      sourceId: 'src_ri_chem_2025_p2',
      questionId: 'q_chem_02',
      questionNumber: '1(b)',
      answerContent: 'Major product: But-2-ene (predominantly trans-but-2-ene). Zaitsev rule dictates that the more substituted and thermodynamically stable alkene is favoured.',
      markSchemeNotes: '1m for but-2-ene, 1m for trans isomer distinction, 1m for hyperconjugation/thermodynamic stability.',
      answerHash: hashNormalizedText('Major product: But-2-ene...'),
      provenance: questions[1].provenance,
      status: 'VERIFIED',
    },
    {
      id: 'ans_chem_03',
      sourceId: 'src_hci_chem_2024_p3',
      questionId: 'q_chem_03',
      questionNumber: '4(a)',
      answerContent: 'Equation: C6H5CH3 + Cl2 -> CH3C6H4Cl + HCl. Mechanism: Electrophilic aromatic substitution with chloronium ion Cl+ generated via AlCl3 Lewis acid.',
      markSchemeNotes: '1m for overall equation, 2m for arenium ion intermediate with correct curly arrows, 1m for regeneration of AlCl3 catalyst.',
      answerHash: hashNormalizedText('Equation: C6H5CH3 + Cl2...'),
      provenance: questions[2].provenance,
      status: 'VERIFIED',
    },
    {
      id: 'ans_chem_04',
      sourceId: 'src_hci_chem_2024_p3',
      questionId: 'q_chem_04',
      questionNumber: '5(a)',
      answerContent: 'Mechanism: Nucleophilic addition. Cyanide ion attacks electrophilic carbonyl carbon forming tetrahedral alkoxide intermediate, which is protonated by HCN, regenerating CN-.',
      markSchemeNotes: '1m for nucleophilic attack curly arrow, 1m for tetrahedral intermediate, 1m for protonation step, 1m for stating regeneration of CN- catalyst.',
      answerHash: hashNormalizedText('Mechanism: Nucleophilic addition...'),
      provenance: questions[3].provenance,
      status: 'VERIFIED',
    },
    {
      id: 'ans_phys_01',
      sourceId: 'src_nyjc_phys_2025_p2',
      questionId: 'q_phys_01',
      questionNumber: '2(a)',
      answerContent: 'Newtons Law: Gravitational force between two point masses is directly proportional to product of masses and inversely proportional to square of separation. Gravitational force provides centripetal force: GMm/r^2 = m(2pi/T)^2 * r. Rearranging gives r^3/T^2 = GM/(4pi^2).',
      markSchemeNotes: '1m for definition of point masses and inverse square law, 2m for equating gravitational force to centripetal acceleration, 1m for algebraic derivation.',
      answerHash: hashNormalizedText('Newtons Law: Gravitational force...'),
      provenance: questions[4].provenance,
      status: 'VERIFIED',
    },
    {
      id: 'ans_math_01',
      sourceId: 'src_vjc_math_2025_p1',
      questionId: 'q_math_01',
      questionNumber: '3',
      answerContent: 'Integration by parts: let u = x, dv/dx = sec^2(x). du/dx = 1, v = tan(x). [x tan x]_0^{pi/4} - int_0^{pi/4} tan(x) dx = pi/4 - [ln|sec x|]_0^{pi/4} = pi/4 - 1/2 ln(2). Volume of revolution = pi * int y^2 dx.',
      markSchemeNotes: '2m for parts substitution, 2m for logarithmic integration of tan(x), 2m for final exact expression.',
      answerHash: hashNormalizedText('Integration by parts...'),
      provenance: questions[5].provenance,
      status: 'VERIFIED',
    },
    {
      id: 'ans_bio_01',
      sourceId: 'src_ejc_bio_2025_p2',
      questionId: 'q_bio_01',
      questionNumber: '1',
      answerContent: 'Competitive inhibitor binds directly to active site: Km increases (lower substrate affinity), Vmax remains unchanged at high substrate concentrations. Non-competitive inhibitor binds to allosteric site altering active site conformation: Km unchanged, Vmax decreases.',
      markSchemeNotes: '2m for competitive inhibitor (Km increases, Vmax unchanged), 2m for non-competitive inhibitor (Km unchanged, Vmax decreases), 1m for active vs allosteric site distinction.',
      answerHash: hashNormalizedText('Competitive inhibitor binds directly...'),
      provenance: questions[6].provenance,
      status: 'VERIFIED',
    },
  ];

  const worksheets: Worksheet[] = [
    {
      id: 'ws_chem_01',
      worksheetNumber: 'WS-01',
      title: 'Organic Chemistry — Hydrocarbons & Halogen Derivatives',
      subject: 'chemistry',
      chapter: 'Organic Chemistry — Hydrocarbons & Halogen Derivatives',
      syllabusVersionId: 'v2026.3',
      version: 1,
      questionCount: 3,
      totalMarks: 10,
      status: 'PUBLISHED',
      sourceCoverage: ['RI', 'HCI'],
      manifest: {
        worksheetId: 'ws_chem_01',
        version: 1,
        subject: 'chemistry',
        chapter: 'Organic Chemistry — Hydrocarbons & Halogen Derivatives',
        questions: ['q_chem_01', 'q_chem_02', 'q_chem_03'],
        totalMarks: 10,
        frozenAt: '2026-09-18T14:00:00Z',
      },
      questionPdfStorageKey: 'worksheets/chemistry/WS-01_Questions.pdf',
      answerPdfStorageKey: 'worksheets/chemistry/WS-01_AnswerKey.pdf',
      generatedAt: '2026-09-18T14:00:00Z',
      updatedAt: '2026-09-18T14:00:00Z',
    },
    {
      id: 'ws_chem_02',
      worksheetNumber: 'WS-02',
      title: 'Organic Chemistry — Carbonyl, Carboxylic & Nitrogen Compounds',
      subject: 'chemistry',
      chapter: 'Organic Chemistry — Carbonyl, Carboxylic & Nitrogen Compounds',
      syllabusVersionId: 'v2026.3',
      version: 1,
      questionCount: 1,
      totalMarks: 4,
      status: 'PUBLISHED',
      sourceCoverage: ['HCI'],
      manifest: {
        worksheetId: 'ws_chem_02',
        version: 1,
        subject: 'chemistry',
        chapter: 'Organic Chemistry — Carbonyl, Carboxylic & Nitrogen Compounds',
        questions: ['q_chem_04'],
        totalMarks: 4,
        frozenAt: '2026-09-18T14:30:00Z',
      },
      questionPdfStorageKey: 'worksheets/chemistry/WS-02_Questions.pdf',
      answerPdfStorageKey: 'worksheets/chemistry/WS-02_AnswerKey.pdf',
      generatedAt: '2026-09-18T14:30:00Z',
      updatedAt: '2026-09-18T14:30:00Z',
    },
    {
      id: 'ws_phys_01',
      worksheetNumber: 'WS-01',
      title: 'Circular Motion & Gravitation',
      subject: 'physics',
      chapter: 'Circular Motion & Gravitation',
      syllabusVersionId: 'v2026.1',
      version: 1,
      questionCount: 1,
      totalMarks: 4,
      status: 'PUBLISHED',
      sourceCoverage: ['NYJC'],
      manifest: {
        worksheetId: 'ws_phys_01',
        version: 1,
        subject: 'physics',
        chapter: 'Circular Motion & Gravitation',
        questions: ['q_phys_01'],
        totalMarks: 4,
        frozenAt: '2026-09-18T15:00:00Z',
      },
      questionPdfStorageKey: 'worksheets/physics/WS-01_Questions.pdf',
      answerPdfStorageKey: 'worksheets/physics/WS-01_AnswerKey.pdf',
      generatedAt: '2026-09-18T15:00:00Z',
      updatedAt: '2026-09-18T15:00:00Z',
    },
    {
      id: 'ws_math_01',
      worksheetNumber: 'WS-01',
      title: 'Calculus (Singapore A-Level)',
      subject: 'mathematics',
      chapter: 'Calculus',
      syllabusVersionId: 'SEAB-9758-Official',
      version: 1,
      questionCount: 1,
      totalMarks: 6,
      status: 'PUBLISHED',
      sourceCoverage: ['VJC'],
      manifest: {
        worksheetId: 'ws_math_01',
        version: 1,
        subject: 'mathematics',
        chapter: 'Calculus',
        questions: ['q_math_01'],
        totalMarks: 6,
        frozenAt: '2026-09-18T15:30:00Z',
      },
      questionPdfStorageKey: 'worksheets/mathematics/WS-01_Questions.pdf',
      answerPdfStorageKey: 'worksheets/mathematics/WS-01_AnswerKey.pdf',
      generatedAt: '2026-09-18T15:30:00Z',
      updatedAt: '2026-09-18T15:30:00Z',
    },
  ];

  const reviewItems: ReviewItem[] = [
    {
      id: 'rev_01',
      entityType: 'QUESTION',
      entityId: 'q_rev_pending_01',
      issueType: 'UNCERTAIN_CLASSIFICATION',
      confidence: 0.58,
      details: {
        rawText: 'Section C: Outline experimental design for calorimetric titration.',
        suggestedChapter: 'The Mole Concept & Stoichiometry',
        alternativeChapter: 'Chemical Energetics & Thermodynamics',
      },
      status: 'PENDING',
      createdAt: '2026-09-19T02:00:00Z',
    },
    {
      id: 'rev_02',
      entityType: 'QUESTION',
      entityId: 'q_rev_pending_02',
      issueType: 'POSSIBLE_DUPLICATE',
      confidence: 0.72,
      details: {
        questionA: 'q_chem_01',
        questionB: 'q_nyjc_chem_variant',
        similarity: 0.81,
        note: 'Near-identical reaction mechanism problem with altered nucleophile concentration.',
      },
      status: 'PENDING',
      createdAt: '2026-09-19T03:30:00Z',
    },
  ];

  return { sources, questions, answers, worksheets, reviewItems };
}
